program: tracking_sweeps.py
name: sweep-cv
method: bayes
metric:
  goal: maximize
  name: tracking/amota
parameters:
  CV_Q_xyz:
    min: 0.1
    max: 1.0
  CV_Q_wlh:
    min: 0.1
    max: 1.0
  CV_Q_vxy:
    min: 0.1
    max: 1.0
  CV_Q_r:
    min: 0.1
    max: 1.0
  CV_R_xyz:
    min: 0.001
    max: 1.0
  CV_R_wlh:
    min: 0.001
    max: 1.0
  CV_R_vxy:
    min: 0.001
    max: 1.0
  CV_R_r:
    min: 0.001
    max: 1.0
command:
  - python
  - tracking_sweeps.py
  - environment=environment
  - +experiment=eval_tracking