program: train_sweeps.py
name: sweep-train_lr
method: bayes
metric:
  goal: minimize
  name: train/best_loss
# parameters:
#   lr:
#     values: [0.0001, 0.00015, 0.0003, 0.001, 0.0015, 0.003]
#   dim:
#     values: [64, 128, 256]
#   depth:
#     values: [2, 4, 6, 8]
#   expand:
#     values: [1, 2]
#   d_state:
#     values: [4, 8, 16, 32]
#   dt_rank:
#     values: [4, 8, 16, 32]
#   d_conv:
#     values: [2, 4, 6, 8]
parameters:
  lr:
    min: 0.0001
    max: 0.003

command:
  - python
  - train_sweeps.py
  - environment=environment
  - +experiment=train_mp