num_class: 7
nms:
  metric: 'iou_bev'
  threshold: 0.08

# ego_transform -> transform tracks from global coord to ego coord
ego_transform: True
ego_frame: 'current' # first, last, current
track:
  # prediction filters: KalmanFilter, ExtendedKalmanFilter, MambaFilter
  motion_prediction_type: {1: 'MambaFilter', 0: 'MambaFilter', 2: 'MambaFilter', 3: 'MambaFilter', 4: 'MambaFilter', 5: 'MambaFilter', 6: 'MambaFilter'}
  # motion models: CV, CA, CTRA, CTRV, Bicycle, SSM
  motion_model: {1: 'SSM', 0: 'SSM', 2: 'SSM', 3: 'SSM', 4: 'SSM', 5: 'SSM', 6: 'SSM'}
  ssm_model: ${model}
  checkpoint: ???
  frequency: 2
  life:
    min_age: {0: 1, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1}
    max_age: {0: 10, 1: 10, 2: 15, 3: 20, 4: 10, 5: 10, 6: 20}
    tent_age: {0: 5, 1: 5, 2: 5, 3: 5, 4: 2, 5: 5, 6: 5}
  score_decay: {0: 0.05, 1: 0.3, 2: 0.2, 3: 0.1, 4: 0.15, 5: 0.15, 6: 0.25}

  # base values, changed when sweeping
  CV_Tuning:
    R_xyz: 0
    R_wlh: 0
    R_vxy: 0
    R_r: 0 
    Q_xyz: 0
    Q_wlh: 0
    Q_vxy: 0
    Q_r: 0

  MAMBA_Tuning:
    R_xyz: 0
    R_wlh: 0
    R_vxy: 0
    R_r: 0 
    Q_xyz: 0
    Q_wlh: 0
    Q_vxy: 0
    Q_r: 0 
  # initial EKF cov
  CTRA: {
    # [x, y, z, w, l, h, v, a, theta, omega]
    1: [10, 10, 10, 10, 10, 10, 10, 10, 1000, 10],
    2: [4, 4, 4, 4, 4, 4, 1000, 4, 1, 0.1],
    4: [10, 10, 10, 10, 10, 10, 10, 10, 1000, 10],
    5: [10, 10, 10, 10, 10, 10, 10, 10, 1000, 10],
    6: [10, 10, 10, 10, 10, 10, 10, 10, 1000, 10],
  }
  CTRV: {
    # [x, y, z, w, l, h, v, theta, omega]
    1: [10, 10, 10, 10, 10, 10, 10, 1000, 10],
    2: [4, 4, 4, 4, 4, 4, 1000, 1, 0.1],
    4: [10, 10, 10, 10, 10, 10, 10, 1000, 10],
    5: [10, 10, 10, 10, 10, 10, 10, 1000, 10],
    6: [10, 10, 10, 10, 10, 10, 10, 1000, 10],
  }
  Bicycle: {
    # [x, y, z, w, l, h, v, a, theta, sigma]
    0: [10, 10, 10, 10, 10, 10, 10000, 10, 10, 10],
    3: [4, 4, 4, 4, 4, 4, 100, 4, 4, 1],
}

association:
  algorithm: 'Hungarian' # Hungarian, Greedy, MNN
  two_stage: True
  metrics: {1: 'giou_bev', 0: 'giou_3d', 2: 'giou_3d', 3: 'giou_3d', 4: 'giou_3d', 5: 'giou_3d', 6: 'giou_3d'}
  threshold1: {1: 1.34, 0: 1.55, 2: 1.31, 3: 1.44, 4: 1.69, 5: 1.25, 6: 1.21}
  threshold2: {0: 1.0}

last_update_limit: 1
class: {0: 'bicycle', 1: 'bus', 2: 'car', 3: 'motorcycle', 4: 'pedestrian', 5: 'trailer', 6: 'truck'}