defaults:
  - model: mamba_motion
  - dataloader: train_mp
  - training: training
  - environment: base_environment
  - sweeps: train
  - loss: loss
  - metrics: metrics
  - logging: wandb

device: cuda