name: EvalSequential
isVal: True
path: ${environment.dataset_base_path}/nuscenes
detector: CenterPointLidar
device: ${device}
batch_size: ${training.batch_size}
shuffle: ${training.shuffle}
num_workers: ${training.num_workers}